version: '2'
services:
  nginx:
    # используем последний стабильный образ nginx
    image: nginx:latest
    # маршрутизируем порты
    ports:
      - "8000:80"
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    # nginx должен общаться с php контейнером
    links:
      - php
  php:
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ./images/php
    # этот образ будет общаться с mysql
    links:
      - mariadb
      - mysql
      - mongo
    # монтируем директорию с проектами
    volumes:
      - ./www:/var/www
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mariadb
    # задаем пароль для root пользователя
    environment:
      MYSQL_ROOT_PASSWORD: secret
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3307"
    volumes:
      - ./mysql:/var/lib/mysql
    # задаем пароль для root пользователя
    environment:
      MYSQL_ROOT_PASSWORD: secret
  mongo:
    image: mongo
    ports:
      - "3308:3308"
    volumes:
      - ./mongo:/var/lib/mongo
    # задаем пароль для root пользователя
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  postgres:
    image: postgres
    restart: always
    ports:
      - "3309:3309"
    volumes:
      - ./postgres:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: selectel
      POSTGRES_USER: selectel
      POSTGRES_DB: selectel
  node:
    image: node
    user: node
    working_dir: /www/hello.test
    environment:
       NODE_ENV: production
    volumes:
      - ./:/node/app
    expose:
      - 8082:8082
    command: "npm start"
  pma:
    # используем последний стабильный образ phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql:mysql
    ports:
      - 8183:80
    environment:
      # прописываем название нашего MySQL хоста
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080